### ISSUE TITLE
Build failure with Qt 5.14

### ISSUE THREAD

**Issue by krop** [Krazy-collection/krazy#12]
Our unstable package tracking krazy from git fails to build with Qt 5.14:

```
[   69s] g++ -c -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -g -g -Wall -Wextra -D_REENTRANT -fPIC -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -I. -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtQml/5.14.0 -isystem /usr/include/qt5/QtQml/5.14.0/QtQml -isystem /usr/include/qt5/QtCore/5.14.0 -isystem /usr/include/qt5/QtCore/5.14.0/QtCore -isystem /usr/include/qt5/QtQml -isystem /usr/include/qt5/QtNetwork -isystem /usr/include/qt5/QtCore -I. -I/usr/lib64/qt5/mkspecs/linux-g++ -o qmlsyntax.o qmlsyntax.cpp
[   71s] qmlsyntax.cpp: In function 'QMap<QString, QList<int> > lint_file(const QString&, bool)':
[   71s] qmlsyntax.cpp:120:57: error: 'const struct QQmlJS::DiagnosticMessage' has no member named 'loc'
[   71s]   120 |                 if (!issues.value(m.message).contains(m.loc.startLine)) {
[   71s]       |                                                         ^~~
[   71s] qmlsyntax.cpp:121:42: error: 'const struct QQmlJS::DiagnosticMessage' has no member named 'loc'
[   71s]   121 |                   issues[m.message] << m.loc.startLine;
[   71s]       |                                          ^~~
[   71s] qmlsyntax.cpp:125:30: error: 'const struct QQmlJS::DiagnosticMessage' has no member named 'loc'
[   71s]   125 |                 lines[0] = m.loc.startLine;
[   71s]       |                              ^~~
[   71s] make[1]: *** [Makefile:411: qmlsyntax.o] Error 1
```

**Comment by winterz** [comment]
should be fixed in commit 3fff664f9be1c3d26039bbff2104d31d443b645d
